# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
State.create([
  { :name => 'Alabama', :abbreviation => 'AL', :description => 'This is a state'},
  { :name => 'Alaska', :abbreviation => 'AK', :description => 'This is a state'},
  { :name => 'Arizona', :abbreviation => 'AZ', :description => 'This is a state'},
  { :name => 'Arkansas', :abbreviation => 'AR', :description => 'This is a state'},
  { :name => 'California', :abbreviation => 'CA', :description => 'This is a state'},
  { :name => 'Colorado', :abbreviation => 'CO', :description => 'This is a state'},
  { :name => 'Connecticut', :abbreviation => 'CT', :description => 'This is a state'},
  { :name => 'Delaware', :abbreviation => 'DE', :description => 'This is a state'},
  { :name => 'Florida', :abbreviation => 'FL', :description => 'This is not a state'},
  { :name => 'Georgia', :abbreviation => 'GA', :description => 'This is a state'},
  { :name => 'Hawaii', :abbreviation => 'HI', :description => 'This is a state'},
  { :name => 'Idaho', :abbreviation => 'ID', :description => 'This is a state'},
  { :name => 'Illinois', :abbreviation => 'IL', :description => 'This is a state'},
  { :name => 'Indiana', :abbreviation => 'IN', :description => 'This is a state'},
  { :name => 'Iowa', :abbreviation => 'IA', :description => 'This is a state'},
  { :name => 'Kansas', :abbreviation => 'KS', :description => 'This is a state'},
  { :name => 'Kentucky', :abbreviation => 'KY', :description => 'This is a state'},
  { :name => 'Louisiana', :abbreviation => 'LA', :description => 'This is a state'},
  { :name => 'Maine', :abbreviation => 'ME', :description => 'This is a state'},
  { :name => 'Maryland', :abbreviation => 'MD', :description => 'This is a state'},
  { :name => 'Massachusetts', :abbreviation => 'MA', :description => 'This is a state'},
  { :name => 'Michigan', :abbreviation => 'MI', :description => 'This is a state'},
  { :name => 'Minnesota', :abbreviation => 'MN', :description => 'This is a state'},
  { :name => 'Mississippi', :abbreviation => 'MS', :description => 'This is a state'},
  { :name => 'Missouri', :abbreviation => 'MO', :description => 'This is a state'},
  { :name => 'Montana', :abbreviation => 'MT', :description => 'This is a state'},
  { :name => 'Nebraska', :abbreviation => 'NE', :description => 'This is a state'},
  { :name => 'Nevada', :abbreviation => 'NV', :description => 'This is a state'},
  { :name => 'New Hampshire', :abbreviation => 'NH', :description => 'This is a state'},
  { :name => 'New Jersey', :abbreviation => 'NJ', :description => 'This is a state'},
  { :name => 'New Mexico', :abbreviation => 'NM', :description => 'This is a state'},
  { :name => 'New York', :abbreviation => 'NY', :description => 'This is a state'},
  { :name => 'North Carolina', :abbreviation => 'NC', :description => 'This is a state'},
  { :name => 'North Dakota', :abbreviation => 'ND', :description => 'This is a state'},
  { :name => 'Ohio', :abbreviation => 'OH', :description => 'This is a state'},
  { :name => 'Oklahoma', :abbreviation => 'OK', :description => 'This is a state'},
  { :name => 'Oregon', :abbreviation => 'OR', :description => 'This is a state'},
  { :name => 'Pennsylvania', :abbreviation => 'PA', :description => 'This is a state'},
  { :name => 'Rhode Island', :abbreviation => 'RI', :description => 'This is a state'},
  { :name => 'South Carolina', :abbreviation => 'SC', :description => 'This is a state'},
  { :name => 'South Dakota', :abbreviation => 'SD', :description => 'This is a state'},
  { :name => 'Tennessee', :abbreviation => 'TN', :description => 'This is a state'},
  { :name => 'Texas', :abbreviation => 'TX', :description => 'This is a state'},
  { :name => 'Utah', :abbreviation => 'UT', :description => 'This is a state'},
  { :name => 'Vermont', :abbreviation => 'VT', :description => 'This is a state'},
  { :name => 'Virginia', :abbreviation => 'VA', :description => 'This is a state'},
  { :name => 'Washington', :abbreviation => 'WA', :description => 'This is a state'},
  { :name => 'West Virginia', :abbreviation => 'WV', :description => 'This is a state'},
  { :name => 'Wisconsin', :abbreviation => 'WI', :description => 'This is a state'},
  { :name => 'Wyoming', :abbreviation => 'WY', :description => 'This is a state'}
])

Park.create([
  { :name => 'Glacier Bay', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Katmai', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Kenai Fjords', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Lake Clark', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Wrangell- St. Elias', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Denali', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Kobuk Valley', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Gates of the Artic', :state_id => 2, :description => 'This is a national park'},
  { :name => 'Saguaro', :state_id => 3, :description => 'This is a national park'},
  { :name => 'Grand Canyon', :state_id => 3, :description => 'This is a national park'},
  { :name => 'Hot Springs', :state_id => 4, :description => 'This is a national park'},
  { :name => 'Death Valley', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Joshua Tree', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Channel Islands', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Sequoia', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Pinnacles', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Kings Canyon', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Yosemite', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Lassen Volcanic', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Redwood', :state_id => 5, :description => 'This is a national park'},
  { :name => 'Mesa Verde', :state_id => 6, :description => 'This is a national park'},
  { :name => 'Great Sand Dunes', :state_id => 6, :description => 'This is a national park'},
  { :name => 'Black Canyon of the Gunnison', :state_id => 6, :description => 'This is a national park'},
  { :name => 'Rocky Mountain', :state_id => 6, :description => 'This is a national park'},
  { :name => 'Dry Tortugas', :state_id => 10, :description => 'This is a national park'},
  { :name => 'Everglades', :state_id => 10, :description => 'This is a national park'},
  { :name => 'Biscayne', :state_id => 10, :description => 'This is a national park'},
  { :name => 'Hawaii Volcanoes', :state_id => 12, :description => 'This is a national park'},
  { :name => 'Haleakala', :state_id => 12, :description => 'This is a national park'},
  { :name => 'Indiana Dunes', :state_id => 15, :description => 'This is a national park'},
  { :name => 'Mammoth Cave', :state_id => 18, :description => 'This is a national park'},
  { :name => 'Acadia', :state_id => 20, :description => 'This is a national park'},
  { :name => 'Isle Royale', :state_id => 23, :description => 'This is a national park'},
  { :name => 'Voyageurs', :state_id => 24, :description => 'This is a national park'},
  { :name => 'Gateway Arch', :state_id => 26, :description => 'This is a national park'},
  { :name => 'Glacier', :state_id => 27, :description => 'This is a national park'},
  { :name => 'Great Basin', :state_id => 29, :description => 'This is a national park'},
  { :name => 'Carlsbad Caverns', :state_id => 32, :description => 'This is a national park'},
  { :name => 'Theodore Roosevelt', :state_id => 35, :description => 'This is a national park'},
  { :name => 'Cooyahoga Valley', :state_id => 36, :description => 'This is a national park'},
  { :name => 'Crater Lake', :state_id => 38, :description => 'This is a national park'},
  { :name => 'Congaree', :state_id => 41, :description => 'This is a national park'},
  { :name => 'Wind Cave', :state_id => 42, :description => 'This is a national park'},
  { :name => 'Badlands', :state_id => 42, :description => 'This is a national park'},
  { :name => 'Great Smoky Mountains', :state_id => 34, :description => 'This is a national park'},
  { :name => 'Big Bend', :state_id => 44, :description => 'This is a national park'},
  { :name => 'Guadalupe Mountains', :state_id => 44, :description => 'This is a national park'},
  { :name => 'Zion', :state_id => 45, :description => 'This is a national park'},
  { :name => 'Bryce Canyon', :state_id => 45, :description => 'This is a national park'},
  { :name => 'Canyonlands', :state_id => 45, :description => 'This is a national park'},
  { :name => 'Capitol Reef', :state_id => 45, :description => 'This is a national park'},
  { :name => 'Arches', :state_id => 45, :description => 'This is a national park'},
  { :name => 'Shenandoah', :state_id => 47, :description => 'This is a national park'},
  { :name => 'Mount Rainier', :state_id => 48, :description => 'This is a national park'},
  { :name => 'Olympic', :state_id => 48, :description => 'This is a national park'},
  { :name => 'North Cascades', :state_id => 48, :description => 'This is a national park'},
  { :name => 'Yellowstone', :state_id => 51, :description => 'This is a national park'},
  { :name => 'Grand Teton', :state_id => 51, :description => 'This is a national park'}
  ])
