# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
State.create([
  { :name => 'Alabama', :abbreviation => 'AL', :description => 'This is a state'},
  { :name => 'Alaska', :abbreviation => 'AK', :description => 'This is a state'},
  { :name => 'Arizona', :abbreviation => 'AZ', :description => 'This is a state'},
  { :name => 'Arkansas', :abbreviation => 'AR', :description => 'This is a state'},
  { :name => 'California', :abbreviation => 'CA', :description => 'This is a state'},
  { :name => 'Colorado', :abbreviation => 'CO', :description => 'This is a state'},
  { :name => 'Connecticut', :abbreviation => 'CT', :description => 'This is a state'},
  { :name => 'Delaware', :abbreviation => 'DE', :description => 'This is a state'},
  { :name => 'Florida', :abbreviation => 'FL', :description => 'This is not a state'},
  { :name => 'Georgia', :abbreviation => 'GA', :description => 'This is a state'},
  { :name => 'Hawaii', :abbreviation => 'HI', :description => 'This is a state'},
  { :name => 'Idaho', :abbreviation => 'ID', :description => 'This is a state'},
  { :name => 'Illinois', :abbreviation => 'IL', :description => 'This is a state'},
  { :name => 'Indiana', :abbreviation => 'IN', :description => 'This is a state'},
  { :name => 'Iowa', :abbreviation => 'IA', :description => 'This is a state'},
  { :name => 'Kansas', :abbreviation => 'KS', :description => 'This is a state'},
  { :name => 'Kentucky', :abbreviation => 'KY', :description => 'This is a state'},
  { :name => 'Louisiana', :abbreviation => 'LA', :description => 'This is a state'},
  { :name => 'Maine', :abbreviation => 'ME', :description => 'This is a state'},
  { :name => 'Maryland', :abbreviation => 'MD', :description => 'This is a state'},
  { :name => 'Massachusetts', :abbreviation => 'MA', :description => 'This is a state'},
  { :name => 'Michigan', :abbreviation => 'MI', :description => 'This is a state'},
  { :name => 'Minnesota', :abbreviation => 'MN', :description => 'This is a state'},
  { :name => 'Mississippi', :abbreviation => 'MS', :description => 'This is a state'},
  { :name => 'Missouri', :abbreviation => 'MO', :description => 'This is a state'},
  { :name => 'Montana', :abbreviation => 'MT', :description => 'This is a state'},
  { :name => 'Nebraska', :abbreviation => 'NE', :description => 'This is a state'},
  { :name => 'Nevada', :abbreviation => 'NV', :description => 'This is a state'},
  { :name => 'New Hampshire', :abbreviation => 'NH', :description => 'This is a state'},
  { :name => 'New Jersey', :abbreviation => 'NJ', :description => 'This is a state'},
  { :name => 'New Mexico', :abbreviation => 'NM', :description => 'This is a state'},
  { :name => 'New York', :abbreviation => 'NY', :description => 'This is a state'},
  { :name => 'North Carolina', :abbreviation => 'NC', :description => 'This is a state'},
  { :name => 'North Dakota', :abbreviation => 'ND', :description => 'This is a state'},
  { :name => 'Ohio', :abbreviation => 'OH', :description => 'This is a state'},
  { :name => 'Oklahoma', :abbreviation => 'OK', :description => 'This is a state'},
  { :name => 'Oregon', :abbreviation => 'OR', :description => 'This is a state'},
  { :name => 'Pennsylvania', :abbreviation => 'PA', :description => 'This is a state'},
  { :name => 'Rhode Island', :abbreviation => 'RI', :description => 'This is a state'},
  { :name => 'South Carolina', :abbreviation => 'SC', :description => 'This is a state'},
  { :name => 'South Dakota', :abbreviation => 'SD', :description => 'This is a state'},
  { :name => 'Tennessee', :abbreviation => 'TN', :description => 'This is a state'},
  { :name => 'Texas', :abbreviation => 'TX', :description => 'This is a state'},
  { :name => 'Utah', :abbreviation => 'UT', :description => 'This is a state'},
  { :name => 'Vermont', :abbreviation => 'VT', :description => 'This is a state'},
  { :name => 'Virginia', :abbreviation => 'VA', :description => 'This is a state'},
  { :name => 'Washington', :abbreviation => 'WA', :description => 'This is a state'},
  { :name => 'West Virginia', :abbreviation => 'WV', :description => 'This is a state'},
  { :name => 'Wisconsin', :abbreviation => 'WI', :description => 'This is a state'},
  { :name => 'Wyoming', :abbreviation => 'WY', :description => 'This is a state'}
])
