# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
State.create([
  { :name => 'Alabama', :abbrevation => 'AL', :description => 'This is a state'},
  { :name => 'Alaska', :abbrevation => 'AK', :description => 'This is a state'},
  { :name => 'Arizona', :abbrevation => 'AZ', :description => 'This is a state'},
  { :name => 'Arkansas', :abbrevation => 'AR', :description => 'This is a state'},
  { :name => 'California', :abbrevation => 'CA', :description => 'This is a state'},
  { :name => 'Colorado', :abbrevation => 'CO', :description => 'This is a state'},
  { :name => 'Connecticut', :abbrevation => 'CT', :description => 'This is a state'},
  { :name => 'Delaware', :abbrevation => 'DE', :description => 'This is a state'},
  { :name => 'District of Columbia', :abbrevation => 'DC', :description => 'This is a state'},
  { :name => 'Florida', :abbrevation => 'FL', :description => 'This is not a state'},
  { :name => 'Georgia', :abbrevation => 'GA', :description => 'This is a state'},
  { :name => 'Hawaii', :abbrevation => 'HI', :description => 'This is a state'},
  { :name => 'Idaho', :abbrevation => 'ID', :description => 'This is a state'},
  { :name => 'Illinois', :abbrevation => 'IL', :description => 'This is a state'},
  { :name => 'Indiana', :abbrevation => 'IN', :description => 'This is a state'},
  { :name => 'Iowa', :abbrevation => 'IA', :description => 'This is a state'},
  { :name => 'Kansas', :abbrevation => 'KS', :description => 'This is a state'},
  { :name => 'Kentucky', :abbrevation => 'KY', :description => 'This is a state'},
  { :name => 'Louisiana', :abbrevation => 'LA', :description => 'This is a state'},
  { :name => 'Maine', :abbrevation => 'ME', :description => 'This is a state'},
  { :name => 'Maryland', :abbrevation => 'MD', :description => 'This is a state'},
  { :name => 'Massachusetts', :abbrevation => 'MA', :description => 'This is a state'},
  { :name => 'Michigan', :abbrevation => 'MI', :description => 'This is a state'},
  { :name => 'Minnesota', :abbrevation => 'MN', :description => 'This is a state'},
  { :name => 'Mississippi', :abbrevation => 'MS', :description => 'This is a state'},
  { :name => 'Missouri', :abbrevation => 'MO', :description => 'This is a state'},
  { :name => 'Montana', :abbrevation => 'MT', :description => 'This is a state'},
  { :name => 'Nebraska', :abbrevation => 'NE', :description => 'This is a state'},
  { :name => 'Nevada', :abbrevation => 'NV', :description => 'This is a state'},
  { :name => 'New Hampshire', :abbrevation => 'NH', :description => 'This is a state'},
  { :name => 'New Jersey', :abbrevation => 'NJ', :description => 'This is a state'},
  { :name => 'New Mexico', :abbrevation => 'NM', :description => 'This is a state'},
  { :name => 'New York', :abbrevation => 'NY', :description => 'This is a state'},
  { :name => 'North Carolina', :abbrevation => 'NC', :description => 'This is a state'},
  { :name => 'North Dakota', :abbrevation => 'ND', :description => 'This is a state'},
  { :name => 'Ohio', :abbrevation => 'OH', :description => 'This is a state'},
  { :name => 'Oklahoma', :abbrevation => 'OK', :description => 'This is a state'},
  { :name => 'Oregon', :abbrevation => 'OR', :description => 'This is a state'},
  { :name => 'Pennsylvania', :abbrevation => 'PA', :description => 'This is a state'},
  { :name => 'Rhode Island', :abbrevation => 'RI', :description => 'This is a state'},
  { :name => 'South Carolina', :abbrevation => 'SC', :description => 'This is a state'},
  { :name => 'South Dakota', :abbrevation => 'SD', :description => 'This is a state'},
  { :name => 'Tennessee', :abbrevation => 'TN', :description => 'This is a state'},
  { :name => 'Texas', :abbrevation => 'TX', :description => 'This is a state'},
  { :name => 'Utah', :abbrevation => 'UT', :description => 'This is a state'},
  { :name => 'Vermont', :abbrevation => 'VT', :description => 'This is a state'},
  { :name => 'Virginia', :abbrevation => 'VA', :description => 'This is a state'},
  { :name => 'Washington', :abbrevation => 'WA', :description => 'This is a state'},
  { :name => 'West Virginia', :abbrevation => 'WV', :description => 'This is a state'},
  { :name => 'Wisconsin', :abbrevation => 'WI', :description => 'This is a state'},
  { :name => 'Wyoming', :abbrevation => 'WY', :description => 'This is a state'}
])
